info:
  contact: {}
paths:
  /hi/:
    get:
      consumes:
      - application/json
      description: Responds with a simple "hi!" message.
      produces:
      - application/json
      responses:
        "200":
          description: SetupRoutes!
          schema:
            type: string
      summary: SetupRoutes Endpoint
      tags:
      - SetupRoutes
swagger: "2.0"
